apiVersion: v1
kind: Pod
metadata:
  name: nedkp
  labels:
    app: nedkp
spec:
  containers:
  - image: pjaehrling/node-express-docker-kubernetes-playground
    name: nedkp
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "200Mi"
        cpu: 2
      # requests:
      #   memory: "100Mi"
      #   cpu: 1
      # -----------------------------------------
      # Kubernetes assignes Quality of Service classes to Pods
      # > Guaranteed: all containers in the pod have CPU & memory limits and no requests
      # > Burstable: all containers have limits and at least one has a request
      # > BestEffort: at least one container has no limit
      #
      # Get the QoS level: kubectl get name -o jsonpath={.status.qosClass}
      #