apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  username: YWRtaW4= # base64: admin
  password: cGFzc3dvcmQ= # base64: password ... woho security at it's best :D
  # could also be a private key etc.